name: gqlapp
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  dio: ^5.0.2
  gql: ^0.14.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_dotenv: ^5.0.2
  graphql_flutter: ^5.1.2
  freezed_annotation: ^2.2.0
  infinite_scroll_pagination: ^3.2.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

  freezed: ^2.3.2
  build_runner: ^2.3.3
  json_serializable: ^6.6.1

flutter:
  uses-material-design: true

  assets:
    - .env.dev

